/** Logo-derived GDK palette — keep in sync with variables.css */
export const logoPalette = {
  orange: "#f58220",
  orangeHover: "#e07018",
  orangeTint: "#fff4e8",
  cyan: "#00adef",
  cyanDark: "#0095c8",
  cyanTint: "#e8f7fd",
  charcoal: "#2d2d2d",
  charcoalDeep: "#1f1f1f",
  white: "#ffffff",
} as const;

export const colorTokens = {
  brand: {
    primary: logoPalette.orange,
    primaryHover: logoPalette.orangeHover,
    secondary: logoPalette.cyanDark,
    secondaryHover: "#0080b0",
    accent: logoPalette.orange,
    accentHover: logoPalette.orangeHover,
  },
  semantic: {
    background: "#fafafa",
    foreground: logoPalette.charcoalDeep,
    surface: logoPalette.white,
    surfaceMuted: "#fafafa",
    surfaceSubtle: "#f5f5f5",
    surfaceRaised: "rgb(255 255 255 / 0.94)",
    card: logoPalette.white,
    cardForeground: logoPalette.charcoalDeep,
    muted: "#f5f5f5",
    mutedForeground: "#5c5c5c",
    accent: logoPalette.cyanTint,
    accentForeground: logoPalette.charcoal,
    border: "#c7e8f5",
    borderSubtle: "#e8f4fa",
    input: "#d9effa",
    ring: logoPalette.cyan,
  },
  text: {
    strong: logoPalette.charcoalDeep,
    body: "#404040",
    muted: "#5c5c5c",
    subtle: "#757575",
    inverse: logoPalette.white,
  },
  status: {
    success: "#2e7d32",
    warning: logoPalette.orange,
    error: "#df1f32",
    info: logoPalette.cyanDark,
  },
  neutral: {
    white: logoPalette.white,
    black: "#000000",
    slate0: logoPalette.white,
    slate50: "#fafafa",
    slate100: "#f5f5f5",
    slate150: "#ececec",
    slate200: "#e0e0e0",
    slate300: "#c9c9c9",
    slate400: "#9e9e9e",
    slate500: "#757575",
    slate600: "#5c5c5c",
    slate700: "#404040",
    slate800: logoPalette.charcoal,
    slate900: logoPalette.charcoal,
    slate950: logoPalette.charcoalDeep,
  },
  product: {
    /** Deep brand surface (hero/footer) — charcoal, not green */
    tealDark: logoPalette.charcoalDeep,
    teal: logoPalette.charcoal,
    processBlue: logoPalette.cyanDark,
    processBlueDark: "#0080b0",
    whatsapp: "#25d366",
  },
  darkMode: {
    background: "#141414",
    surface: logoPalette.charcoalDeep,
    surfaceMuted: logoPalette.charcoal,
    card: logoPalette.charcoalDeep,
    foreground: "#f8fafc",
    mutedForeground: "#d4d4d4",
    primaryHover: "#f69a3d",
    secondaryHover: logoPalette.cyan,
    border: "rgb(153 224 250 / 0.18)",
  },
} as const;

export type ColorTokens = typeof colorTokens;
