export const shadowTokens = {
  global: "0 14px 34px color-mix(in srgb, var(--brand-charcoal-950) 10%, transparent)",
  globalDark: "0 12px 28px color-mix(in srgb, var(--brand-charcoal-950) 35%, transparent)",
  xs: "0 1px 2px color-mix(in srgb, var(--brand-charcoal-950) 5%, transparent)",
  sm: "0 8px 18px color-mix(in srgb, var(--brand-charcoal-950) 6%, transparent)",
  buttonPrimary: "0 12px 24px color-mix(in srgb, var(--brand-accent) 28%, transparent)",
  buttonPrimaryStrong: "0 18px 38px color-mix(in srgb, var(--brand-accent) 34%, transparent)",
  buttonSecondary: "0 12px 24px color-mix(in srgb, var(--secondary) 24%, transparent)",
  submit: "0 10px 24px color-mix(in srgb, var(--brand-accent) 24%, transparent)",
  submitHover: "0 14px 30px color-mix(in srgb, var(--brand-accent) 30%, transparent)",
  focus: "0 0 0 4px color-mix(in srgb, var(--ring) 24%, transparent)",
  cardSubtle: "0 3px 12px color-mix(in srgb, var(--brand-charcoal-950) 3.5%, transparent)",
  cardMedium: "0 8px 22px color-mix(in srgb, var(--brand-charcoal-950) 5.5%, transparent)",
  cardElevated: "0 10px 28px color-mix(in srgb, var(--brand-charcoal-950) 5.5%, transparent)",
  cardHoverElevation: "0 14px 32px color-mix(in srgb, var(--brand-charcoal-950) 8.5%, transparent)",
  card: "0 8px 22px color-mix(in srgb, var(--brand-charcoal-950) 5.5%, transparent)",
  cardSoft: "0 10px 28px color-mix(in srgb, var(--brand-charcoal-950) 5.5%, transparent)",
  cardHover: "0 14px 32px color-mix(in srgb, var(--brand-charcoal-950) 8.5%, transparent)",
  nav: "0 8px 24px color-mix(in srgb, var(--brand-charcoal-950) 8%, transparent)",
  megaMenu: "0 22px 52px color-mix(in srgb, var(--brand-charcoal-950) 16%, transparent)",
  heroPanel: "0 16px 42px color-mix(in srgb, var(--brand-charcoal-950) 16%, transparent)",
  heroBadge: "0 12px 28px color-mix(in srgb, var(--brand-charcoal-950) 18%, transparent)",
  floatingAction: "0 20px 44px color-mix(in srgb, var(--ds-color-whatsapp) 32%, transparent)",
} as const;

export type ShadowTokens = typeof shadowTokens;
